export let lazyimages=
[
    'https://m.media-amazon.com/images/I/814ePfNubRL._AC_UL320_.jpg',
    'https://m.media-amazon.com/images/I/81OC0ojxH6L._AC_UL320_.jpg',
    'https://m.media-amazon.com/images/I/71GFYocYzhL._AC_UL320_.jpg',
    'https://m.media-amazon.com/images/I/61olN3oDvYL._AC_UL320_.jpg',
    'https://m.media-amazon.com/images/I/612Y5tw1x5L._AC_UL320_.jpg',
    'https://m.media-amazon.com/images/I/71GLMJ7TQiL._AC_UY218_.jpg',
    'https://m.media-amazon.com/images/I/71gm8v4uPBL._AC_UY218_.jpg',
    'https://m.media-amazon.com/images/I/71fVoqRC0wL._AC_UY218_.jpg',
    'https://m.media-amazon.com/images/I/71ZOtNdaZCL._AC_UY218_.jpg',
    'https://m.media-amazon.com/images/I/71T5NVOgbpL._AC_UY218_.jpg',
    'https://m.media-amazon.com/images/I/81UT07JsBqL._AC_UY218_.jpg',
    'https://m.media-amazon.com/images/I/810KHyQ4WcL._AC_UY218_.jpg',
    'https://m.media-amazon.com/images/I/911TJ1CDbLL._AC_UY218_.jpg',
    'https://m.media-amazon.com/images/I/61hxpOV817L._AC_UY218_.jpg',
    'https://m.media-amazon.com/images/I/71C4pfJ7ecL._AC_UY218_.jpg',
    'https://m.media-amazon.com/images/I/71AvQd3VzqL.jpg',
    'https://m.media-amazon.com/images/I/71flXufDnbL.jpg',
    'https://m.media-amazon.com/images/I/71V--WZVUIL._AC_UY218_.jpg',
    'https://m.media-amazon.com/images/I/716uVx3Wr5L._AC_UY218_.jpg',
    'https://m.media-amazon.com/images/I/71BoiXkrEmL._AC_UY218_.jpg'
]